// List of words to be loaded into recognizer
module.exports =    [
    ["ZERO",            "Z IY R OW"             ]
,   ["ONE",             "W AH N"                ]
,   ["ONE(2)",          "HH W AH N"             ]
,   ["TWO",             "T UW"                  ]
,   ["THREE",           "TH R IY"               ]
,   ["FOUR",            "F AO R"                ]
,   ["FIVE",            "F AY V"                ]
,   ["SIX",             "S IH K S"              ]
,   ["SEVEN",           "S EH V AH N"           ]
,   ["EIGHT",           "EY T"                  ]
,   ["NINE",            "N AY N"                ]

,   ["TEN",             "T EH N"                ]
,   ["ELEVEN",          "IH L EH V AH N"        ]
,   ["ELEVEN(2)",       "IY L EH V AH N"        ]
,   ["TWELVE",          "T W EH L V"            ]
,   ["THIRTEEN",        "TH ER T IY N"          ]
,   ["FOURTEEN",        "F AO R T IY N"         ]
,   ["FIFTHTEEN",       "F IH F TH T IY N"      ]
,   ["SIXTEEN",         "S IH K S T IY N"       ]
,   ["SEVENTEEN",       "S EH V AH N T IY N"    ]
,   ["EIGHTEEN",        "EY T IY N"             ]
,   ["NINETEEN",        "N AY N T IY N"         ]

,   ["TWENTY",          "T W EH N T IY"         ]
,   ["THIRTY",          "TH ER D IY"            ]
,   ["FORTY",           "F AO R T IY"           ]
,   ["FIFTY",           "F IH F T IY"           ]
,   ["SIXTY",           "S IH K S T IY"         ]
,   ["SEVENTY",         "S EH V AH N T IY"      ]
,   ["EIGHTY",          "EY T IY"               ]
,   ["NINETY",          "N AY N T IY"           ]

,   ["HUNDRED",         "HH AH N D R AH D"      ]
,   ["HUNDRED(2)",      "HH AH N D R IH D"      ]
,   ["HUNDRED(3)",      "HH AH N ER D"          ]
,   ["HUNDRED(4)",      "HH AH N D ER D"        ]
,   ["THOUSAND",        "TH AW Z AH N D"        ]
,   ["THOUSAND(2)",     "TH AW Z AH N"          ]
,   ["MILLION",         "M IH L Y AH N"         ]
,   ["BILLION",         "B IH L Y AH N"         ]
,   ["TRILLION",        "T R IH L Y AH N"       ]

,   ["AND",             "AH N D"                ]
,   ["AND(2)",          "AE N D"                ]

,   ["HELLO",           "HH AH L OW"            ]
,   ["HELLO (2)",       "HH EH L OW"            ]
,   ["WORLD",           "W ER L D"              ]

,   ["WE",              "W IY"                  ]
,   ["MADE",            "M EY D"                ]
,   ["IT",              "IH T"                  ]

,   ["BLACKJACK",       "B L AE K JH AE K"      ]
,   ["HIT",             "HH IH T"               ]
,   ["ME",              "M IY"                  ]
,   ["BABY",            "B EY B IY"             ]
,   ["STAND",           "S T AE N D"            ]
,   ["I",               "AY"                    ]
,   ["HOLD",            "HH OW L D"             ]
,   ["BUST",            "B AH S T"              ]
,   ["SPLIT",           "S P L IH T"            ]
,   ["QUIT",            "K W IH T"              ]
,   ["WIN",             "W IH N"                ]
,   ["LOOK",            "L UH K"                ]
,   ["OVER",            "OW V ER"               ]
,   ["THERE",           "DH EH R"               ]
,   ["DOUBLE",          "D AH B AH L"           ]
,   ["DOWN",            "D AW N"                ]
,   ["CUT",             "K AH T"                ]
,   ["THE",             "DH AH"                 ]
,   ["THE (2)",         "DH IY"                 ]
,   ["DECK",            "D EH K"                ]

,   ["PAY",             "P EY"                  ]
,   ["UP",              "AH P"                  ]
,   ["ANOTHER",         "AH N AH DH ER"         ]
,   ["ROUND",           "R AW N D"              ]
,   ["MORE",            "M AO R"                ]
,   ["BEER",            "B IH R"                ]
,   ["WHISKEY",         "W IH S K IY"           ]
,   ["WHISKEY(2)",      "HH W IH S K IY"        ]
,   ["COUNTING",        "K AW N T IH NG"        ]
,   ["CARDS",           "K AA R D Z"            ]
,   ["FIGHT",           "F AY T"                ]

,   ["CASH",            "K AE SH"               ]
,   ["OUT",             "AW T"                  ]
,   ["POKER",           "P OW K ER"             ]
,   ["CHIP",            "CH IH P"               ]
,   ["FACE",            "F EY S"                ]
,   ["STACK",           "S T AE K"              ]
,   ["EM",              "EH M"                  ]
,   ["HIGH",            "HH AY"                 ]
,   ["LEG",             "L EH G"                ]
,   ["DOWN",            "D AW N"                ]
,   ["YAK",             "Y AE K"                ]
,   ["UP",              "AH P"                  ]

];
